### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by parithy** [PhieF/CarnetDocumentation#48]
Once next cloud account is added, app starts to crash

**Comment by parithy** [comment]
Errors:


04-29 18:11:39.734 12526 12526 D AndroidRuntime: Shutting down VM
04-29 18:11:39.735 12526 12526 E AndroidRuntime: FATAL EXCEPTION: main
04-29 18:11:39.735 12526 12526 E AndroidRuntime: Process: com.spisoft.quicknote, PID: 12526
04-29 18:11:39.735 12526 12526 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at com.spisoft.quicknote.Note.setPath(Note.java:63)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at com.spisoft.quicknote.databases.RecentHelper.getLatestNotes(RecentHelper.java:232)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at com.spisoft.quicknote.browser.RecentNoteListFragment.getNotes(RecentNoteListFragment.java:54)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at com.spisoft.quicknote.browser.NoteListFragment$1.run(NoteListFragment.java:143)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6682)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
04-29 18:11:39.735 12526 12526 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
04-29 18:11:39.736  5868 14321 D Debug   : !@DumpState : SHIP
04-29 18:11:39.737  5868 14321 D Debug   : !@DumpState : debug level:0x4f4c
04-29 18:11:39.737  5868 14321 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
04-29 18:11:39.737  5868 14321 W ActivityManager:   Force finishing activity com.spisoft.quicknote/.MainActivity
04-29 18:11:39.737  5868 14321 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root is not base activity
04-29 18:11:39.739  5868 14321 D ActivityManager: moveToFront() : reason=finishActivity adjustFocus setFocusedActivity isAttached=true TaskRecord{1e15e3cd0 #4645 A=com.sec.android.app.launcher U=0 StackId=0 sz=1}
04-29 18:11:39.740  5868 14321 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null
04-29 18:11:39.740  5868 14321 D ActivityManager: setFocusStackUnchecked: reason=finishActivity adjustFocus setFocusedActivity focusCandidate=ActivityStack{4706ff4d0 stackId=0, 2 tasks} caller=com.android.server.am.ActivityStack.moveToFront:874 com.android.server.am.ActivityStackSupervisor.moveActivityStackToFront:2006

**Comment by PhieF** [comment]
Hi, 

what is your carnet version on android ? 

Is it the play store apk ? 

Thanks !

**Comment by parithy** [comment]
the log was from the version before yesterday's update. just now in phone. But the issue is present in current May 2019 version as well (0.1-20190504.1921)

**Comment by PhieF** [comment]
That's really weird because for me, this line

```
com.spisoft.quicknote.Note.setPath(Note.java:63)
```
doesn't exist anymore

do you think you could check if the log has changed ? sorry for that...
